browser:
  headless: true
  timeout_ms: 30000
  viewport:
    width: 1920
    height: 1080

  user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36"

security:
  allowed_domains:
    - "youtube.com"
    - "google.com"
    - "wikipedia.org"
    - "github.com"
    - "stackoverflow.com"
    - "reddit.com"
    - "python.org"
    - "docs.python.org"
    - "pypi.org"

  blocked_domains:
    - "*.onion"       # Dark web
    - "localhost"
    - "127.0.0.1"

  max_redirects: 5
  max_page_size_mb: 50

search:
  default_engine: "google"
  max_results: 10

  engines:
    google:
      url: "https://www.google.com/search?q={query}"
      result_selector: "div.g"
      title_selector: "h3"
      link_selector: "a"
      snippet_selector: "div[data-sncf], div.VwiC3b"

    bing:
      url: "https://www.bing.com/search?q={query}"
      result_selector: "li.b_algo"
      title_selector: "h2"
      link_selector: "a"
      snippet_selector: "p"
